config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"

  get "/login" => "sessions#new"
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get "/signup" => "users#new"
  post '/signup' => "users#create"

  get '/cards/find_by_properties'
  post '/cards/find_by_properties' => 'cards#filter_search'

  get '/cards/reserved_list' => 'cards#reserved_list'

  get '/cards/search_results' => 'cards#search_results'
  get '/cards/card_names' => 'cards#card_names'
  get '/cards/card_names_with_editions' => 'cards#card_names_with_editions'
  get '/cards/:edition/' => 'cards#edition'
  get '/cards/artists/:artist' => 'cards#artist'
  get '/cards/color/:color' => 'cards#color'

  get '/cards/:edition/:name' => 'cards#show', as: 'card'

  get '/about' => 'application#about'

  get '/editions' => 'editions#index'

  get '/editions/open_booster_pack/' => 'editions#open_booster_pack'
  post '/editions/open_booster_pack/' => 'editions#open_booster_pack'

  get '/hand_odds_calculator' => 'application#hand_odds_calculator'
  post '/decks/calculate_custom_hand_odds' => 'decks#calculate_custom_hand_odds'
  
  post '/cards/update_prices' => 'cards#update_prices'

  resources :users, except: [:index]
  resources :decks, except: [:create]
  get '/decks/:id/sample_hand' => 'decks#sample_hand'

  resources :collections, except: [:edit, :create]
  
  #js-created cards
  post '/decks/create'
  post '/collections/create'

  #render error 404 if route doesn't exist
  match '*path' => 'application#render_404', via: :all
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :collections_cards, dependent: :destroy
  has_many :cards, through: :collections_cards

  validates :name, presence: true, uniqueness: { scope: :user_id }

  belongs_to :user
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :build_collection, only: [:create]
  before_action :redirect_unless_logged_in, only: [:new]

  def new
    @collection = Collection.new
  end

  def create
    @collection.valid? ? (redirect_to collections_path) : (render :new)
  end

  def index
    @collections = current_user.collections
  end

  def show
    @collection = Collection.includes(:cards).find(params[:id])
  end

  private

    def build_collection
      card_list = params[:collections_cards][:list].split(/ \r\n/)
  
      @collection = Collection.new(name: collection_params[:name], user_id: current_user.id)
  
      return nil unless @collection.save
  
      @collections_cards = card_list.map do | card_string | 
        #split on 'x ' coming after digit(s), and ' - ', e.g.: '1x Dack Fayden - Conspiracy' -> ['1', 'Dack Fayden', 'Conspiracy']
        copies, name, edition = card_string.split(/(?<=\d)x | - /)
        
        card_id = Card.select(:id).find_by(name: name, edition: edition).id
        
        next if card_id.nil?
      
        { copies: copies.to_i, collection_id: @collection.id, card_id: card_id }
      end.compact
  
      CollectionsCard.transaction do
        CollectionsCard.insert_all(@collections_cards)
      end
    end

    def collection_params
      params.require(:collection).permit(:name, :user_id)
    end
end

app/helpers/collection_helper.rb
module CollectionHelper
  def calculate_collection_value(collection)
    value = collection.collections_cards.map do | collection_card | 
              card = collection_card.card
              card_kingdom_price = card.prices[1].to_f || 0  
              collection_card.copies * card_kingdom_price
            end.sum.round(2)

    number_with_delimiter(value)
  end


  def display_collection(collection)
    collection.collections_cards.map do | collection_card |
      card = collection_card.card
      name, edition, price, copies = [card.name, card.edition, card.prices[1], collection_card.copies]

      "<li>#{copies}x #{link_to(name, card_path(edition, name))} - $#{price}</li>"
    end.join.html_safe
  end

end

app/views/collections/index.html.erb
<% title("My Collections") %>

<h1> Your Collections </h1> 

<% @collections.each do | collection | %>
  <li> <%= link_to collection.name, collection_path(collection) %> </li>
<% end %>

<h3> <%= link_to 'Create New Collection', new_collection_path %> </h3>

app/views/collections/new.html.erb
<% title('New Collection') %>

<h1 class='text-center' id='collection-page-title'> My New Collection </h1>

<%= form_for(@collection) do | form | %>

  <div>
    <%= form.label :collection_name, style: 'margin-top: 15px;' %>
    <%= form.text_field :name %>
  </div>

  <br><br>

  <%= fields_for :collections_cards do | dc | %>
    <div>
      <div>
        <%= dc.label :copies %>
        <%= dc.number_field :copies, min: 1, max: 9, value: 1, style: 'margin-bottom: 10px; margin-left: 15px;' %>
      </div>

      <%= dc.label :card %>

      <span style='margin-bottom: 10px; margin-left: 30px;'>
        <%= form_with url: '#', method: "GET", local: true, id: 'collectionCardSearch' do %>
          <%= text_field_tag :search, params[:search], id: 'collectionCardFind', list: 'collectionBuildSearch', required: true, autocomplete: 'off', placeholder: 'Add a Card'%>
          <datalist id="collectionBuildSearch"> </datalist>
        <% end %>
        <button id='addCollectionCard'>Add Card</button>
      </span>

      <div> 
        <%= dc.text_area(:list, class: 'card-list') %> 
      </div>
    </div>

  <% end %>
  <button id="createCollection" style='margin-top: 50px;'> Create Collection </button>
<% end %>

app/views/collections/show.html.erb
<% title("Your Collection") %>

<h1> <%= @collection.name %> </h1>

<h4> Your collection is worth $<%= calculate_collection_value(@collection) %> </h4>

<%= display_collection(@collection) %>