config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"

  get "/login" => "sessions#new"
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get "/signup" => "users#new"
  post '/signup' => "users#create"

  get '/cards/find_by_properties'
  post '/cards/find_by_properties' => 'cards#filter_search'

  get '/cards/reserved_list' => 'cards#reserved_list'

  get '/cards/search_results' => 'cards#search_results'
  get '/cards/card_names' => 'cards#card_names'
  get '/cards/card_names_with_editions' => 'cards#card_names_with_editions'
  get '/cards/:edition/' => 'cards#edition'
  get '/cards/artists/:artist' => 'cards#artist'
  get '/cards/color/:color' => 'cards#color'

  get '/cards/:edition/:name' => 'cards#show', as: 'card'

  get '/about' => 'application#about'

  get '/editions' => 'editions#index'

  get '/editions/open_booster_pack/' => 'editions#open_booster_pack'
  post '/editions/open_booster_pack/' => 'editions#open_booster_pack'

  get '/hand_odds_calculator' => 'application#hand_odds_calculator'
  post '/decks/calculate_custom_hand_odds' => 'decks#calculate_custom_hand_odds'
  
  post '/cards/update_prices' => 'cards#update_prices'

  resources :users, except: [:index]
  resources :decks, except: [:create]
  get '/decks/:id/sample_hand' => 'decks#sample_hand'

  resources :collections, except: [:edit, :create]
  
  #js-created cards
  post '/decks/create'
  post '/collections/create'

  #render error 404 if route doesn't exist
  match '*path' => 'application#render_404', via: :all
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :decks_cards, dependent: :destroy
  has_many :cards, through: :decks_cards
  has_many :card_types, through: :cards
  has_many :colors, through: :cards

  validates :name, presence: true, uniqueness: { scope: :user_id }

  belongs_to :user
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  include DeckHandStats
  
  before_action :set_deck, only: [:show, :sample_hand, :destroy]
  before_action :set_shuffled_deck, only: [:show, :sample_hand]
  before_action :redirect_unless_logged_in, only: [:new, :show, :index]
  before_action :deny_unauthorized_deck_access, only: [:show, :sample_hand, :edit, :update, :destroy]
  before_action :build_deck, only: [:create]

  def new
    @deck = Deck.new
  end

  def create
    @deck.valid? ? (redirect_to decks_path) : (render :new)
  end

  def destroy
    @deck.destroy
    redirect_to decks_path
  end

  def calculate_custom_hand_odds
    render json: calculate_odds
  end

  def sample_hand
    @sample_hand = draw_hand(@shuffled_deck_cards)
    @card_types = card_classifications(@sample_hand)
    @hand_frequencies = card_frequencies(@sample_hand)
    @deck_frequencies = card_frequencies(@shuffled_deck_cards)

    @multivar_args = multivar_geo_freq_args(@hand_frequencies, @deck_frequencies).values
  end

  def show
    @deck_frequencies = card_frequencies(@shuffled_deck_cards)
    @card_types = card_classifications(@shuffled_deck_cards).to_json
  end

  def index
    @decks = current_user.decks
  end

  private

    def set_deck
      @deck = Deck.find(params[:id])
    end

    def set_shuffled_deck
      @shuffled_deck_cards = shuffled_deck(@deck)
    end

    def deny_unauthorized_deck_access
      redirect_to root_path unless logged_in? && @deck.user_id == current_user.id
    end

    def calculate_odds
      deck_size = params[:deck_size].to_i
      cards_drawn = params[:cards_drawn].to_i
      multivar_args = hand_and_deck_card_counts(params).values
      
      Probability.multivariate_hypergeometric_distribution(deck_size, cards_drawn, *multivar_args)
    end
    
    #create the deck and then its decks_cards
    def build_deck
      cards_with_quantities = params[:decks_cards][:list].split(/ \r\n/)
      
      deck_name = deck_params[:name]

      @deck = Deck.create({ name: deck_name, user_id: current_user.id })

      return nil unless @deck.id

      #this will later be used to let the user know if any of the cards they entered were invalid and didn't work
      unfound_cards = []

      decks_cards = cards_with_quantities.map do | card_string |
        edition_match = card_string.match(/[a-z]+(?=\])/i)
        edition = edition_match[0] if edition_match
        
        #remove set name in brackets if it exists, then split on 'x ' coming after digits
        copies, name = card_string.sub(/ \[[a-z]+\]/i, '').split(/(?<=\d)x /)
        
        #find cheapest card variant if no edition/set is specified
        card_id = find_specific_or_cheapest_card_variant_id(name, edition)

        if card_id.nil?
          unfound_cards << name
          puts "thank u,"; next
        end
      
        { copies: copies.to_i, deck_id: @deck.id, card_id: card_id }
      end.compact

      DecksCard.transaction do
        DecksCard.insert_all(decks_cards)
      end
    end

    def deck_params
      params.require(:deck).permit(:name, :user_id, :colors, :card_types, decks_cards_attributes: [:card_id, :copies])
    end

end

app/helpers/deck_helper.rb
module DeckHelper
  
  def generate_mana_curve_data(deck)
    frequencies = {}

    mana_costs = deck.map(&:converted_mana_cost).compact

    (0..mana_costs.max).each { | cost | frequencies[cost] = mana_costs.count(cost) }

    #map mana cost frequencies into an { x-axis : X, y-axis : Y } format
    graph_data = frequencies.map { | key, value | { 'x' => key, 'y' => value } }

    graph_data.to_json
  end

  def shuffled_deck(deck)
    deck.decks_cards.includes(:card).each.with_object([]) do | deck_card, cards |
      deck_card.copies.times { cards << deck_card.card }
    end.shuffle
  end

  def draw_hand(deck, n=7)
    deck.first(n).sort_by(&:card_type)
  end

  #rotates each card by two degrees times its distance from the center (7 cards)
  def set_rotation_angle(idx)
    angle = (2 * idx) - 6
    "transform: rotate(#{angle}deg)"
  end

  def next_eight_cards(deck)
    deck[7..-1].first(8)
  end

  #CardKingdom sells all cards for a minimum of $0.25 which can inflate the reported value
  #return TCG Player price if CK price is $0.25.
  #return MTGFish Price if CK price is N/A
  def determine_appropriate_price(prices)
    return 0 if prices.empty?

    prices.map!(&:to_f)

    mtg_fish, card_kingdom, tcg_player = prices

    return card_kingdom unless card_kingdom <= 0.25
    return tcg_player unless tcg_player.zero?
    mtg_fish
  end

  def calculate_deck_value(cards)
    values = cards.map(&:prices) 

    total_value = values.map { | prices | determine_appropriate_price(prices) }.sum.round(4)
    
    number_to_currency(total_value)
  end

  def sort_by_number_and_name_desc(cards, deck_frequencies)
    cards.uniq(&:name).sort_by { | card | [ -@deck_frequencies[card.name], card.name ] }
  end

  #return the id of the exact match if user specifies edition, otherwise find cheapest version's id
  def find_specific_or_cheapest_card_variant_id(name, edition = nil)
    return Card.find_by(name: name, edition: edition).id unless edition.nil?
    return Card.find_by(name: name).id if ApplicationHelper::LANDS.include?(name)

    Card.select(:id, :prices, :name)
        .where(name: name)
        .reject { | card | card.prices[1] == "N/A" }
        .min_by { | card | card.prices[1].to_i }
        &.id
  end
end

app/views/decks/_form.html.erb
<%= form_for(deck) do | form | %>

  <div>
    <%= form.label :deck_name, style: 'margin-top: 15px;' %>
    <%= form.text_field :name %>
  </div>

  <br><br>

  <%= fields_for :decks_cards do | dc | %>
    <div>
      <div>
        <%= dc.label :copies %>
        <%= dc.number_field :copies, min: 1, max: 4, value: 1, style: 'margin-bottom: 10px; margin-left: 15px;' %>
      </div>

      <%= dc.label :card %>

      <span style= 'margin-bottom: 10px; margin-left: 30px;'>
        <%= form_with url: '#', method: "GET", local: true, id: 'deckCardSearch' do %>
          <%= text_field_tag :search, params[:search], id: 'deckCardFind', list: 'deckBuildSearch', required: true, autocomplete: 'off', placeholder: 'Add a Card'%>
          <datalist id="deckBuildSearch"> </datalist>
        <% end %>
        <button id='addCard'>Add Card</button>
      </span>

      <div style='margin-top: 55px;'>
        <div style='margin-bottom: 5px;'>
          <%= dc.label :copies %>
          <%= dc.number_field :land_copies, min: 1, max: 24, value: 1, style: 'margin-left: 20px;' %>
        </div>
        
        <%= dc.label :basic_land %>
        <%= dc.select(:land_name, options_for_select(['Plains', 'Island', 'Swamp', 'Mountain', 'Forest'])) %>
        <button id="addLand"> Add Basic Land </button>
      </div>

      <%= dc.text_area(:list, class: 'card-list') %> 
      <div id='card-count' style="font-weight: 600;"> Total Cards: 0 </div>
    </div>

  <% end %>
  <button id="createDeck" style='margin-top: 50px;'> Create Deck </button>
<% end %>

app/views/decks/index.html.erb
<% title("My Decks") %>

<h1> Your Decks </h1> 

<% @decks.all.each do | deck | %>
  <li> <%= link_to deck.name, deck_path(deck) %> </li>
<% end %>

<h3> <%= link_to 'Create New Deck', new_deck_path %> </h3>

app/views/decks/new.html.erb
<h1 id='collection-page-title' class='text-center'> New Deck </h1>

<%= render partial: "form", locals: { deck: @deck, user: current_user, cards: @cards } %>

app/views/decks/sample_hand.html.erb
<% title(@deck.name) %>

<h1 class="text-center"> <%= @deck.name %> </h1>
<h4 class="text-center"> Turn 1 </h4>
<br>

<div class="row margin-bottom" >

  <% @sample_hand.each_with_index do | card, idx | %>
    <div class='col-sm-1 filter'> 
      <div class="deck-show-card-name"> <%= truncate_at_three_words(card.name) %> </div> 
      <%= image_tag card.img_url, class: 'hand-card', style: "#{set_rotation_angle(idx)}" %>
    </div>
  <% end %>

  <div class="stats" >
    <b> <%= link_to("Deck Overview", deck_path(@deck)) %> </b>
    <h4> Lands: <%= @card_types['lands'] %> </h4>
    <h4> Spells: <%= @card_types['spells'] %> </h4>
    <h4> Artifacts: <%= @card_types['artifacts'] %> </h4>
    <h4> Creatures: <%= @card_types['creatures'] %> </h4>
    <h4> Hand Odds: <%= Probability.multivariate_hypergeometric_distribution(@shuffled_deck_cards.size, cards_drawn = 7, *@multivar_args) %>% </h4>
  </div>

</div>

<div class="row">
  <h1 class="text-center"> Upcoming Cards </h1>
  <br>
  <br>
  <% next_eight_cards(@shuffled_deck_cards).each.with_index(2) do | card, idx | %>
    <div class = "col-sm-1 filter">
      <div class="text-center"> Turn <%= idx %> </div>
      <div class="deck-show-card-name"> <%= truncate_at_three_words(card.name) %> </div>
        
      <%= image_tag card.img_url, class: 'hand-card' %>
    </div>
  <% end %>

  <div id="deck-holder" class="col-sm-2 pad-4" value="8"> 
    <p id="card-counter"> Card 8 of <%= @shuffled_deck_cards.size %> </p>
    <%= image_tag 'card back', id: "deck-holder-card-back", size: '223x310' %>
    <% @shuffled_deck_cards[7..-1].reverse.each.with_index(8) do | card,  idx | %>
      <%= image_tag card.img_url, class: 'deck-display', id: "deck-card-#{idx}", size: '223x310' %> 
    <% end %>
  </div>

</div>

app/views/decks/show.html.erb
<% title("#{@deck.name} - Breakdown") %>
<div class='container-fluid'>
  <h1 class='text-center'> <%= @deck.name.titleize %> Overview </h1>

  <h3 id="sample_hand" style="margin-bottom: 1px;"> <%= link_to("Generate Sample Hand", "/decks/#{@deck.id}/sample_hand") %> 
    <%= link_to "Delete", @deck, method: :delete, data: { confirm: "Are you sure you want to delete this deck?" }, style: "float: right;" %>  
  </h3>

  <div class="row">
    <div class="col-sm-3">
      <h4 id="deck-list-title"> Cards </h4>
      
      <% sort_by_number_and_name_desc(@shuffled_deck_cards, @deck_frequencies).each do | card | %>
        <div>
          <div class="btn btn-sm" data-toggle="popover" data-content='<%= image_tag(card.img_url) %>' title=" "> 
            <%= "#{@deck_frequencies[card.name]}x" %> <%= link_to(card.name, card_path(card.edition, card.name), class: "popover-js") %> 
          </div>
        </div>
      <% end %>

      <h5 id="deck-value"> Total Value: <%= calculate_deck_value(@shuffled_deck_cards) %></h5>
    </div>
    
    <!-- Deck display. Cards are inserted into theh DOM one on top of the other, leading to reverse order. 
    First cards applied are the bottom n-6 cards to be loaded later. Top cards (the second loop) are loaded immediately.-->
    <div class="large-deck col-sm-4" id="deck-holder" value="1"> 
      <p id="card-counter"> Card 1 of <%= @shuffled_deck_cards.size %> </p>
      <%= image_tag 'card back', id: "deck-holder-card-back" %>
      
      <% @shuffled_deck_cards[0..-6].each.with_index(1) do | card,  idx | %>
        <%= image_tag "wall-4-light.png", image_placeholder: card.hi_res_img.sub('/large','/normal'), class: "deck-display large #{card.edition.downcase} lazy", id: "deck-card-#{idx}" %> 
      <% end %>

      <% @shuffled_deck_cards[-5..-1].each.with_index(@shuffled_deck_cards.size - 4) do | card,  idx | %>
        <%= image_tag card.hi_res_img.sub('/large','/normal'), class: "deck-display large #{card.edition.downcase}", id: "deck-card-#{idx}" %> 
      <% end %>

    </div>
    
    <div>
      <div id="pieChartContainer" class="col-sm-3" data-json="<%= @card_types %>" > </div>
      <div id="splineContainer" class="col-sm-3" data-json="<%= generate_mana_curve_data(@shuffled_deck_cards) %>" ></div>
    </div>
    
  </div>

</div>