config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"

  get "/login" => "sessions#new"
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get "/signup" => "users#new"
  post '/signup' => "users#create"

  get '/cards/find_by_properties'
  post '/cards/find_by_properties' => 'cards#filter_search'

  get '/cards/reserved_list' => 'cards#reserved_list'

  get '/cards/search_results' => 'cards#search_results'
  get '/cards/card_names' => 'cards#card_names'
  get '/cards/card_names_with_editions' => 'cards#card_names_with_editions'
  get '/cards/:edition/' => 'cards#edition'
  get '/cards/artists/:artist' => 'cards#artist'
  get '/cards/color/:color' => 'cards#color'

  get '/cards/:edition/:name' => 'cards#show', as: 'card'

  get '/about' => 'application#about'

  get '/editions' => 'editions#index'

  get '/editions/open_booster_pack/' => 'editions#open_booster_pack'
  post '/editions/open_booster_pack/' => 'editions#open_booster_pack'

  get '/hand_odds_calculator' => 'application#hand_odds_calculator'
  post '/decks/calculate_custom_hand_odds' => 'decks#calculate_custom_hand_odds'
  
  post '/cards/update_prices' => 'cards#update_prices'

  resources :users, except: [:index]
  resources :decks, except: [:create]
  get '/decks/:id/sample_hand' => 'decks#sample_hand'

  resources :collections, except: [:edit, :create]
  
  #js-created cards
  post '/decks/create'
  post '/collections/create'

  #render error 404 if route doesn't exist
  match '*path' => 'application#render_404', via: :all
end

app/views/layouts/_login_modal.html.erb
<div class='modal fade' id="loginModalCenter" tabindex='-1' role='dialog' aria-hidden='true'>
  <div class='modal-dialog modal-dialog-centered' role='document'>
    <div class='login-modal-content'>
      <div class='modal-header'>
        <h1 class='text-center'> Sign in </h1>

        <h3 id='loginError'></h3>
        
        <div class='text-center'>
          <%= form_for :user, remote: true, url: url_for(controller: 'sessions', action: 'create'), html: { id: 'loginForm' } do |f| %>
            <h5>
              <div> <%= f.label :name %> </div>            
              <%= f.text_field :name, id: 'login_name', autocomplete: 'user', required: true %>
            </h5>
            
            <h5>
              <div> <%= f.label :password %> </div>
              <%= f.password_field :password, id: 'login_password', required: true %>
            </h5>

            <div class="margin-top-30 margin-bottom-20">
              <%= f.submit "Log in" %>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<h5 class='navbar'>
  <%= link_to("Sign Up", "#", data: { toggle: :modal, target: "#signupModalCenter" }, class: 'nav-link') unless logged_in? %>
  <%= link_to("Log In",  "#", data: { toggle: :modal, target: "#loginModalCenter"  }, class: 'nav-link') unless logged_in? %>
  <%= link_to("Home", root_path, class: 'nav-link') unless current_page?(root_path) %>  

  <div class='drop-down'>
    <a class='drop-button'>Tools ▼</a>
    <div class='drop-down-content'>
      <%= link_to("Calculator",             "/hand_odds_calculator",       class: 'nav-link') %>
      <%= link_to("Generate Booster Packs", "/editions/open_booster_pack", class: 'nav-link') %>
    </div>
  </div> 
 
  <%= link_to("My Decks",       decks_path,       class: 'nav-link') if logged_in? %>
  <%= link_to("My Collections", collections_path, class: 'nav-link') if logged_in? %>
  <%= link_to("Find Cards by Property", "/cards/find_by_properties", class: 'nav-link') %>
  <%= link_to("About", "/about",    class: 'nav-link') %>
  <%= link_to("Log Out", "/logout", class: 'nav-link', method: :delete) if logged_in? %>
  
  <span class='account-settings'> 
    <%= link_to("Account Settings", user_path(current_user), class: 'nav-link') if logged_in? %> 
  </span>

  <%= render "layouts/search_bar" %>

  <% unless logged_in? %>
    <%= render "layouts/login_modal" %>
    <%= render "layouts/signup_modal" %>
  <% end %>

</h5>

app/views/layouts/_search_bar.html.erb
<div class="search-bar">
  <%= form_with url: '/cards/search_results', method: "GET", local: true do %>
    <%= text_field_tag :search, params[:search], list: 'autocomplete', required: true, class: 'search-input', autocomplete: 'off', placeholder: 'Card Search', minlength: 2 %>
    <datalist id="autocomplete"> </datalist>
  <% end %>
</div>

app/views/layouts/_signup_modal.html.erb
<div class='modal fade' id="signupModalCenter" tabindex='-1' role='dialog' aria-hidden='true'>
  <div class='modal-dialog modal-dialog-centered' role='document'>
    <div class='signup-modal-content'>
      <div class='modal-header'>
        <h1 class='text-center margin-bottom-20'> Sign up </h1>

          <h5 id='signupError'></h5>

          <%= form_for :user, remote: true, url: url_for(controller: 'users', action: 'create'), html: { id: 'signupForm' } do | f | %>
            <h5>
              <div><%= f.label :name %></div>
              <div><%= f.text_field :name, required: true %></div>
            </h5>

            <h5>
              <div><%= f.label :email %></div>
              <div><%= f.text_field :email %></div>
            </h5>

            <h5>
              <div><%= f.label :password %></div>
              <div><%= f.password_field :password, required: true %></div>
            </h5>

            <h5>
              <div><%= f.label :password_confirmation, "Verify Password" %></div>
              <div><%= f.password_field :password_confirmation, required: true %></div>
            </h5>
          <div class="margin-top-40 margin-bottom-20">
            <%= f.submit 'Create Account' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title> 
      <%= content_for?(:title) ? yield(:title) : 'MTG Catalogue' %> 
    </title>

    <meta charset="utf-8">
    <meta name="description" content="Magic: The Gathering Catalogue and Deck Builder">
    <meta name="author" content="Daniel Lempesis">

    <%= favicon_link_tag asset_path('favicon.ico'), rel: 'icon', type: 'image/x-icon' %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://cdn1.mtggoldfish.com" crossorigin>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <%= stylesheet_link_tag    :application, media: :all, data: { turbolinks: { track: :reload } } %>
    <%= javascript_include_tag :application, data: { turbolinks: { track: :reload } } %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>